CREATE TABLE `user_character` (
  `character_id` int(20) NOT NULL AUTO_INCREMENT COMMENT '角色id',
  `zone` int(11) NOT NULL DEFAULT 0 COMMENT '区服',
  `user_id` int(20) NOT NULL DEFAULT 0 COMMENT '用户id',
  `name` varchar(20) NOT NULL DEFAULT '' COMMENT '名字',
  `race` int(11) NOT NULL DEFAULT 0 COMMENT '种族',
  `job` int(11) NOT NULL DEFAULT 0 COMMENT '职业',
  `level` int(11) NOT NULL DEFAULT 1 COMMENT '等级',
  `body_level` int(11) NOT NULL DEFAULT 1 COMMENT '肉身等级',
  `att` int(11) NOT NULL DEFAULT 0 COMMENT '攻击',
  `def` int(11) NOT NULL DEFAULT 0 COMMENT '防御',
  `hp` int(11) NOT NULL DEFAULT 0 COMMENT '血量',
  `crit` int(11) NOT NULL DEFAULT 0 COMMENT '暴击率',
  `dodge` int(11) NOT NULL DEFAULT 0 COMMENT '闪避率',
  `experience` int(11) NOT NULL DEFAULT 0 COMMENT '经验值',
  `experience_speed` int(11) NOT NULL DEFAULT 0 COMMENT '经验值获取速度',
  `gold` int(11) NOT NULL DEFAULT 0 COMMENT '灵石',
  `prestige` int(11) NOT NULL DEFAULT 0 COMMENT '声望',
  `money` int(11) NOT NULL DEFAULT 0 COMMENT '仙玉',
  `max_stage` int(11) NOT NULL DEFAULT 0 COMMENT '已通关关卡',
  `current_stage` int(11) NOT NULL DEFAULT 0 COMMENT '所在关卡',
  `sect` int(11) NOT NULL DEFAULT 0 COMMENT '门派',
  `position` int(11) NOT NULL DEFAULT 0 COMMENT '官位',
  `coordinate` int(11) NOT NULL DEFAULT 0 COMMENT '所在坐标',
  `is_hide` tinyint NOT NULL DEFAULT 0 COMMENT '是否隐身 0-否 1-是',
  `extra_info` text COMMENT '扩展信息',
  `create_user` varchar(20) NOT NULL DEFAULT '' COMMENT '创建人',
  `update_user` varchar(20) NOT NULL DEFAULT '' COMMENT '修改人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_delete` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除 0-否 1-是',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '版本号',
  PRIMARY KEY (`character_id`),
  FOREIGN KEY (`user_id`) REFERENCES user_account(id),
  INDEX `idx_character_id` (`character_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色表';
