CREATE TABLE `monster` (
  `id` int(20) NOT NULL AUTO_INCREMENT COMMENT '怪物id',
  `map_id` varchar(20) NOT NULL DEFAULT '' COMMENT '地图id',
  `map_name` varchar(20) NOT NULL DEFAULT '' COMMENT '地图名称',
  `name` varchar(20) NOT NULL DEFAULT '' COMMENT '名字',
  `race` int(11) NOT NULL DEFAULT 0 COMMENT '种族',
  `job` int(11) NOT NULL DEFAULT 0 COMMENT '职业',
  `level` int(11) NOT NULL DEFAULT 1 COMMENT '等级',
  `att` int(11) NOT NULL DEFAULT 0 COMMENT '攻击',
  `def` int(11) NOT NULL DEFAULT 0 COMMENT '防御',
  `hp` int(11) NOT NULL DEFAULT 0 COMMENT '血量',
  `crit` int(11) NOT NULL DEFAULT 0 COMMENT '暴击率',
  `dodge` int(11) NOT NULL DEFAULT 0 COMMENT '闪避率',
  `coordinate` int(11) NOT NULL DEFAULT 0 COMMENT '所在坐标',
  `is_hide` tinyint NOT NULL DEFAULT 0 COMMENT '是否隐身 0-否 1-是',
  `extra_info` text COMMENT '扩展信息',
  `create_user` varchar(20) NOT NULL DEFAULT '' COMMENT '创建人',
  `update_user` varchar(20) NOT NULL DEFAULT '' COMMENT '修改人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_delete` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除 0-否 1-是',
  `version` int(11) NOT NULL DEFAULT '0' COMMENT '版本号',
  PRIMARY KEY (`id`),
  INDEX `idx_id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='怪物表';
